                    const THEME_PRESETS = [
                        // Classic & Bold
                        { cat: '🔴 Classic & Bold', id: 'maroon', name: 'Maroon', css: 'linear-gradient(135deg,#800000,#c0392b)' },
                        { cat: '🔴 Classic & Bold', id: 'blue', name: 'Blue', css: '#2980b9' },
                        { cat: '🔴 Classic & Bold', id: 'glossyred', name: 'Glossy Red', css: 'linear-gradient(135deg,#cf2e2e,#a31111)' },
                        { cat: '🔴 Classic & Bold', id: 'crimson', name: 'Crimson', css: 'linear-gradient(135deg,#1a0000,#dc143c)' },
                        { cat: '🔴 Classic & Bold', id: 'royal_blue', name: 'Royal Blue', css: 'linear-gradient(135deg,#00091e,#1338be)' },
                        { cat: '🔴 Classic & Bold', id: 'emerald', name: 'Emerald', css: 'linear-gradient(135deg,#002d1f,#00875a)' },
                        // Warm & Vibrant
                        { cat: '🌅 Warm & Vibrant', id: 'sunset', name: 'Sunset', css: 'linear-gradient(135deg,#f83600,#f9d423)' },
                        { cat: '🌅 Warm & Vibrant', id: 'golden', name: 'Golden', css: 'linear-gradient(135deg,#b8860b,#ffd700)', style: 'color:#1a1a1a;' },
                        { cat: '🌅 Warm & Vibrant', id: 'rose', name: 'Rose', css: 'linear-gradient(135deg,#b76e79,#fad4dc)', style: 'color:#4a1520;' },
                        { cat: '🌅 Warm & Vibrant', id: 'lava_lamp', name: 'Lava Lamp', css: 'linear-gradient(135deg,#ff6b35,#ffcd3c)', style: 'color:#1a0a00;' },
                        { cat: '🌅 Warm & Vibrant', id: 'mango_tango', name: 'Mango Tango', css: 'linear-gradient(135deg,#ff6f00,#ff9800,#ffca28)', style: 'color:#3e2723;' },
                        { cat: '🌅 Warm & Vibrant', id: 'desert_twilight', name: 'Desert Twilight', css: 'linear-gradient(135deg,#ff6b6b,#c44569,#574b90)', style: 'color:#fff; text-shadow:0 2px 12px rgba(0,0,0,0.3);' },
                        { cat: '🌅 Warm & Vibrant', id: 'champagne_dusk', name: 'Champagne Dusk', css: 'linear-gradient(135deg,#f5e6d3,#e8c9a0,#d4a574)', style: 'color:#3d2914;' },
                        { cat: '🌅 Warm & Vibrant', id: 'copper_rust', name: 'Copper Rust', css: 'linear-gradient(135deg,#5c3317,#8b4513,#cd7f32)', style: 'color:#fff8e7; text-shadow:0 2px 8px rgba(0,0,0,0.4);' },
                        { cat: '🌅 Warm & Vibrant', id: 'sand_dune', name: 'Sand Dune', css: 'linear-gradient(135deg,#c2996b,#6b4c2a)' },
                        { cat: '🌅 Warm & Vibrant', id: 'volcanic', name: 'Volcanic', css: 'linear-gradient(135deg,#0a0000,#c0392b)', style: 'color:#ffa500;' },
                        // Cool & Nature
                        { cat: '🌿 Cool & Nature', id: 'ocean', name: 'Ocean', css: 'linear-gradient(135deg,#0f2027,#2c5364)' },
                        { cat: '🌿 Cool & Nature', id: 'forest', name: 'Forest', css: 'linear-gradient(135deg,#134e5e,#71b280)' },
                        { cat: '🌿 Cool & Nature', id: 'mint', name: 'Mint', css: 'linear-gradient(135deg,#00b09b,#96c93d)' },
                        { cat: '🌿 Cool & Nature', id: 'purple_haze', name: 'Purple', css: 'linear-gradient(135deg,#360033,#0b8793)' },
                        { cat: '🌿 Cool & Nature', id: 'jade_garden', name: 'Jade Garden', css: 'linear-gradient(135deg,#081c15,#1b4332,#40916c)', style: 'color:#d8f3dc; text-shadow:0 0 12px rgba(149,213,178,0.5);' },
                        { cat: '🌿 Cool & Nature', id: 'northern_lights', name: 'Northern Lights', css: 'linear-gradient(135deg,#0b1026,#1a3a5c,#00c9a7)', style: 'color:#7fffd4; text-shadow:0 0 10px rgba(0,201,167,0.6);' },
                        { cat: '🌿 Cool & Nature', id: 'glacier_glass', name: 'Glacier Glass', css: 'linear-gradient(135deg,#e0f7fa,#80deea,#00838f)', style: 'color:#004d40;' },
                        { cat: '🌿 Cool & Nature', id: 'ice_storm', name: 'Ice Storm', css: 'linear-gradient(135deg,#e8f4f8,#4a90a4)', style: 'color:#0a2a3d;' },
                        // Dark & Moody
                        { cat: '🌙 Dark & Moody', id: 'modern', name: 'Dark', css: '#1a1c23' },
                        { cat: '🌙 Dark & Moody', id: 'midnight', name: 'Midnight', css: 'linear-gradient(135deg,#0a0a0a,#16213e)' },
                        { cat: '🌙 Dark & Moody', id: 'charcoal', name: 'Charcoal', css: 'linear-gradient(135deg,#1c1c1e,#3a3a3c)' },
                        { cat: '🌙 Dark & Moody', id: 'dark_teal', name: 'Teal', css: 'linear-gradient(135deg,#0d1b1e,#14532d)' },
                        { cat: '🌙 Dark & Moody', id: 'dark_purple', name: 'Elite Purple', css: 'linear-gradient(135deg,#12001f,#4b0082)' },
                        { cat: '🌙 Dark & Moody', id: 'arctic_noir', name: 'Arctic Noir', css: 'linear-gradient(135deg,#0a0f14,#0d1f2d)', style: 'color:#d4f1f9;' },
                        { cat: '🌙 Dark & Moody', id: 'obsidian_flame', name: 'Obsidian Flame', css: 'linear-gradient(135deg,#0d0d0d,#1a1a1a,#b71c1c)', style: 'color:#ff8a80; text-shadow:0 0 15px rgba(255,138,128,0.6);' },
                        { cat: '🌙 Dark & Moody', id: 'monochrome_ink', name: 'Monochrome Ink', css: 'linear-gradient(135deg,#0a0a0a,#1f1f1f,#3d3d3d)', style: 'color:#f5f5f5;' },
                        { cat: '🌙 Dark & Moody', id: 'deep_space', name: 'Deep Space', css: 'linear-gradient(to bottom,#000000,#000814)', style: 'color:#c8d8ff;' },
                        // Light & Minimal
                        { cat: '✨ Light & Minimal', id: 'clean_white', name: 'White', css: '#fff', style: 'color:#111; border: 1px solid #bbb;' },
                        { cat: '✨ Light & Minimal', id: 'flat_gray', name: 'Gray', css: 'linear-gradient(135deg,#bdc3c7,#2c3e50)' },
                        { cat: '✨ Light & Minimal', id: 'steel_professional', name: 'Steel Pro', css: 'linear-gradient(135deg,#263238,#37474f,#546e7a)', style: 'color:#eceff1;' },
                        { cat: '✨ Light & Minimal', id: 'soft_lavender', name: 'Soft Lavender', css: 'linear-gradient(135deg,#e8eaf6,#c5cae9,#9fa8da)', style: 'color:#311b92;' },
                        { cat: '✨ Light & Minimal', id: 'pastel_dream', name: 'Pastel Dream', css: 'linear-gradient(135deg,#fce4ec,#e1bee7,#b3e5fc)', style: 'color:#4a148c;' },
                        { cat: '✨ Light & Minimal', id: 'sakura_bloom', name: 'Sakura Bloom', css: 'linear-gradient(135deg,#ffc0cb,#ffb7c5,#ff69b4)', style: 'color:#4a1528;' },
                        { cat: '✨ Light & Minimal', id: 'pearl_oyster', name: 'Pearl Oyster', css: 'linear-gradient(135deg,#faf8f5,#ede4d9,#d4c4b0)', style: 'color:#5d4e37;' },
                        // Soft Light — light background + dark readable text
                        { cat: '☀️ Soft Light', id: 'cream_canvas', name: 'Cream Canvas', css: 'linear-gradient(135deg,#fffef7,#f8f4eb,#f0ebe0)', style: 'color:#1a1a1a;' },
                        { cat: '☀️ Soft Light', id: 'sky_mist', name: 'Sky Mist', css: 'linear-gradient(135deg,#f0f9ff,#e0f2fe,#bae6fd)', style: 'color:#0c4a6e;' },
                        { cat: '☀️ Soft Light', id: 'mint_frost', name: 'Mint Frost', css: 'linear-gradient(135deg,#f0fdf4,#dcfce7,#bbf7d0)', style: 'color:#14532d;' },
                        { cat: '☀️ Soft Light', id: 'blush_petal', name: 'Blush Petal', css: 'linear-gradient(135deg,#fff5f7,#fce7f3,#fbcfe8)', style: 'color:#831843;' },
                        { cat: '☀️ Soft Light', id: 'lemon_zest', name: 'Lemon Zest', css: 'linear-gradient(135deg,#fefce8,#fef9c3,#fef08a)', style: 'color:#422006;' },
                        { cat: '☀️ Soft Light', id: 'linen_natural', name: 'Linen Natural', css: 'linear-gradient(135deg,#faf7f2,#f0ebe3,#e8dfd0)', style: 'color:#3d3229;' },
                        { cat: '☀️ Soft Light', id: 'cloud_soft', name: 'Cloud Soft', css: 'linear-gradient(135deg,#ffffff,#f8fafc,#f1f5f9)', style: 'color:#0f172a; border:1px solid #e2e8f0;' },
                        { cat: '☀️ Soft Light', id: 'seafoam_light', name: 'Seafoam Light', css: 'linear-gradient(135deg,#ecfdf5,#d1fae5,#a7f3d0)', style: 'color:#064e3b;' },
                        { cat: '☀️ Soft Light', id: 'apricot_cream', name: 'Apricot Cream', css: 'linear-gradient(135deg,#fff7ed,#ffedd5,#fed7aa)', style: 'color:#7c2d12;' },
                        { cat: '☀️ Soft Light', id: 'ivory_elegant', name: 'Ivory Elegant', css: 'linear-gradient(135deg,#fffff8,#fafaf0,#f5f5dc)', style: 'color:#2c2c2c;' },
                        { cat: '☀️ Soft Light', id: 'honey_dew', name: 'Honey Dew', css: 'linear-gradient(135deg,#fffbeb,#fef3c7,#fde68a)', style: 'color:#78350f;' },
                        { cat: '☀️ Soft Light', id: 'powder_blue', name: 'Powder Blue', css: 'linear-gradient(135deg,#eff6ff,#dbeafe,#bfdbfe)', style: 'color:#1e3a5f;' },
                        // Luxury & Premium
                        { cat: '👑 Luxury & Premium', id: 'luxury_gold', name: 'Lux Gold', css: '#0a0a0a', style: 'color:#ffd700; text-shadow:0 0 8px rgba(255,215,0,0.6);' },
                        { cat: '👑 Luxury & Premium', id: 'velvet_plum', name: 'Velvet Plum', css: 'linear-gradient(135deg,#1a0a14,#2d1b33,#6b2d5c)', style: 'color:#f8e1f4; text-shadow:0 0 15px rgba(248,225,244,0.4);' },
                        { cat: '👑 Luxury & Premium', id: 'aurora', name: 'Aurora', css: 'linear-gradient(135deg,#0f0c29,#24243e)', style: 'color:#a78bfa;' },
                        // Neon & Cyber
                        { cat: '⚡ Neon & Cyber', id: 'neon', name: 'Neon', css: '#000', style: 'color:#00ffcc; text-shadow:0 0 8px #00ffcc;' },
                        { cat: '⚡ Neon & Cyber', id: 'cyber_punk', name: 'Cyber Punk', css: 'linear-gradient(135deg,#0d0221,#1a0533)', style: 'color:#ff00ff; text-shadow:0 0 8px #ff00ff;' },
                        { cat: '⚡ Neon & Cyber', id: 'toxic_lime', name: 'Toxic Lime', css: 'linear-gradient(135deg,#001a00,#007a0d)', style: 'color:#aaff00; text-shadow:0 0 8px #aaff00;' },
                        { cat: '⚡ Neon & Cyber', id: 'electric_violet', name: 'Electric Violet', css: 'linear-gradient(135deg,#2e1065,#4c1d95,#7c3aed)', style: 'color:#e9d5ff; text-shadow:0 0 12px rgba(167,139,250,0.7);' },
                        { cat: '⚡ Neon & Cyber', id: 'retro_wave', name: 'Retro Wave', css: 'linear-gradient(135deg,#240046,#ff0080,#7928ca)', style: 'color:#00d4ff; text-shadow:0 0 12px #00d4ff;' },
                        { cat: '⚡ Neon & Cyber', id: 'holographic_prism', name: 'Holographic', css: 'linear-gradient(135deg,#667eea,#764ba2,#f093fb,#f5576c)', style: 'color:#fff; text-shadow:0 0 10px rgba(255,255,255,0.5);' },
                        // Cosmic & Mystic
                        { cat: '🌌 Cosmic & Mystic', id: 'cosmic_dust', name: 'Cosmic Dust', css: 'linear-gradient(135deg,#020111,#2e0854)', style: 'color:#e8d5ff;' },
                        { cat: '🌌 Cosmic & Mystic', id: 'blood_moon', name: 'Blood Moon', css: 'radial-gradient(ellipse at center,#8b0000,#0a0000)', style: 'color:#ff3300; text-shadow:0 0 8px #ff0000;' }
                    ];